### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by BillyDM** [RustAudio/baseview#101]
Here I compiled a short TODO list for baseview:

## Highest priority:
- [ ] A way for the user to manually close a baseview window from their code.

## High priority:
- [ ] Get keyboard modifiers from the OS (but not from keyboard inputs because some DAWs will capture this). For example, some OS's will send modifiers via mouse events. Modifier changes should be sent to the user as its own event.
- [ ] A way to open/close modal dialogs (this is a sure way a plugin can always get text input).

## Medium priority:
- [ ] A way to open/close additional windows.
- [ ] Copy/paste functionality.

## Lower priority:
- [ ] A way for the user to set the mouse icon from their code.
- [ ] A way for the user to hide & lock the mouse cursor in place (for knobs and sliders and such). When in this locked mode, send some kind-of raw mouse movement events to the user.
- [ ] Functionality to drag & drop from an external window.

**Comment by robbert-vdh** [comment]
>  Get keyboard modifiers from the OS (but not from keyboard inputs because some DAWs will capture this). For example, some OS's will send modifiers via mouse events. Modifier changes should be sent to the user as its own event.

#117 I submitted a month a go adds this.

> A way for the user to manually close a baseview window from their code.

Isn't that what `WindowHandle::close()` does?

**Comment by BillyDM** [comment]
> Isn't that what `WindowHandle::close()` does?

Oh yes. I need to check that off the list.

**Comment by prokopyl** [comment]
Closing this in favor of the newly-created milestones organization. 🙂
