### ISSUE TITLE
Development Sprint

### ISSUE THREAD

**Issue by BillyDM** [RustAudio/baseview#168]
# Development Sprint

## Highest priority:
- [ ] Ability to set cursor icon
    - [X] Linux (X11)
    - [ ] Windows
    - [ ] MacOS
- [ ] Drag & Drop functionality
    - [ ] Linux (X11)
    - [ ] Windows
    - [ ] Mac
- [ ] [#152](https://github.com/RustAudio/baseview/issues/152) Add a set_focus(bool) interface for getting and losing keyboard focus
    - [ ] Linux (X11)
    - [ ] Windows
    - [ ] Mac

## Medium Priority:
- [ ] [#126](https://github.com/RustAudio/baseview/issues/126) macOS DAW UIs become very unresponsive after plugin window is opened
- [ ] [#145](https://github.com/RustAudio/baseview/issues/145) Add support for Windows 7 and 8
- [ ] [#107](https://github.com/RustAudio/baseview/issues/107) [Windows] VST using imgui-rs and baseview changes Ableton scaling and doesn't get the right window when Windows scaling isn't set to 100% 
- [ ] [#129](https://github.com/RustAudio/baseview/issues/129) The initial click is ignored on macOS, requires mouse movement before the second click works correctly

## Lower Priority:
- [ ] [#122](https://github.com/RustAudio/baseview/issues/122) Handling window creation failures
- [ ] [#142](https://github.com/RustAudio/baseview/issues/142) Panic in Reaper on Linux when closing plugin window

**Comment by BillyDM** [comment]
I'll take adding drag & drop functionality to X11

**Comment by BillyDM** [comment]
@glowcoil  said they will update the X11 backend to use the x11rb dependency instead of xcb.

**Comment by BillyDM** [comment]
@prokopyl said they will add support for versions "0.5" and "0.6" of raw_window_handle.

**Comment by prokopyl** [comment]
Closing this in favor of the newly-created milestones organization. 🙂
